use same dilogarithm function in FORTRAN and C++ module for 2-loop corrections
This modification

1) fixes the following compilation error on MacOS when creating
   libDSZ.dynlib:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Undefined symbols for architecture x86_64:

  "himalaya::dilog(double)", referenced from:

      himalaya::mssm_twoloophiggs::delta_ma2_2loop_at_as_mst1_eq_mst2(double, double, double, double, double, double, double, double, double, double, double) in DSZHiggs.cpp.o

      himalaya::mssm_twoloophiggs::delta_mh2_2loop_at_as(double, double, double, double, double, double, double, double, double, double, double, int) in DSZHiggs.cpp.o

ld: symbol(s) not found for architecture x86_64
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2) ensures that the same precision is used to evaluate the 2-loop
   corrections both in the FORTRAN and in the C++ module